# Generated by Django 2.2.4 on 2020-04-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_thoughtsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addeventmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_username', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('descr', models.CharField(max_length=100)),
                ('contactno', models.IntegerField(unique=True)),
            ],
        ),
    ]
