# Generated by Django 2.2.4 on 2020-04-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addeventmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='status',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
